# Generated by Django 5.2.8 on 2025-11-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='country name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='country code')),
                ('phone_code', models.CharField(max_length=10, unique=True, verbose_name='phone code')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country_flags/', verbose_name='flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='city name')),
                ('is_popular', models.BooleanField(default=False, help_text='Designates whether the city is marked as popular.', verbose_name='is popular')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='city_icons/', verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('country', models.ForeignKey(help_text='The country this city belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='users.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the search was performed', verbose_name='searched at')),
                ('city', models.ForeignKey(help_text='The city that was searched for', on_delete=django.db.models.deletion.CASCADE, to='users.city', verbose_name='city')),
                ('user', models.ForeignKey(help_text='The user who performed the search', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
