# Generated by Django 5.2.8 on 2025-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temp',
            field=models.BooleanField(default=True, help_text='Designates whether the user is a temporary user.', verbose_name='temporary user'),
        ),
    ]
