# Generated by Django 5.2.8 on 2025-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_city_usersearchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, null=True, verbose_name='flag'),
        ),
    ]
