# Generated by Django 5.2.8 on 2025-11-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='phone code'),
        ),
    ]
