# Generated by Django 5.2.8 on 2025-11-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_country_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchhistory',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='custumer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer id'),
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='search',
            field=models.CharField(blank=True, help_text='The search term entered by the user', max_length=255, null=True, verbose_name='search term'),
        ),
    ]
