# Generated by Django 5.2.8 on 2025-11-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usersearchhistory_city_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='custumer_id',
            new_name='customer_id',
        ),
    ]
