# Generated by Django 5.2.8 on 2025-12-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email', models.EmailField(help_text='The email address of the subscriber', max_length=254, verbose_name='email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user subscribed', verbose_name='subscribed at')),
                ('user', models.ForeignKey(help_text='The user who subscribed to the newsletter', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'unique_together': {('user', 'email')},
            },
        ),
    ]
