# Generated by Django 5.2.8 on 2025-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, help_text='Device token for push notifications', max_length=512, null=True, verbose_name='device token'),
        ),
    ]
