# Generated by Django 5.2.8 on 2025-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='news_icons/', verbose_name='Icon')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
            ],
        ),
    ]
