# Generated by Django 5.2.8 on 2026-02-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_redeemedoffer'),
        ('news', '0002_newsarticle_created_at_newsarticle_updated_at'),
        ('users', '0011_alter_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The business category this news article relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.businesscategory', verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='city',
            field=models.ForeignKey(blank=True, help_text='The city this news article is relevant to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city', verbose_name='City'),
        ),
    ]
