# Generated by Django 5.2.8 on 2026-02-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_category_newsarticle_city'),
        ('users', '0011_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='city',
            field=models.ForeignKey(blank=True, help_text='The city this news article is relevant to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='users.city', verbose_name='City'),
        ),
    ]
