# Generated by Django 5.2.8 on 2026-02-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_redeemedoffer'),
        ('news', '0004_alter_newsarticle_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The business category this news article relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='business.businesscategory', verbose_name='Business Category'),
        ),
    ]
