# Generated by Django 5.2.8 on 2025-11-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the card', max_length=100, unique=True)),
                ('duration', models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('1_month', '1 Month')], help_text='Duration of the card validity', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the card', max_digits=6)),
                ('short_description', models.CharField(blank=True, help_text='Short description of the card', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the card is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the card was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the card was last updated')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the benefit', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the benefit', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or class for the benefit', max_length=100, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='card.card')),
            ],
        ),
    ]
