# Generated by Django 5.2.8 on 2025-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_cardbenefit_options_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user card is active.', verbose_name='is active'),
        ),
    ]
