# Generated by Django 5.2.8 on 2025-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_usercardhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardhistory',
            name='action',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('renew', 'Renew'), ('auto_expire', 'Auto Expire'), ('cancel', 'Cancel')], max_length=20, verbose_name='action'),
        ),
    ]
