# Generated by Django 5.2.8 on 2026-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_usercardhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('1_month', '1 Month'), ('1_year', '1 Month')], help_text='Duration of the card validity', max_length=20),
        ),
    ]
