# Generated by Django 5.2.8 on 2025-12-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('api_key', models.CharField(help_text='API key for Google Maps services', max_length=255, verbose_name='Google Maps API Key')),
            ],
            options={
                'verbose_name': 'Google Maps Setting',
                'verbose_name_plural': 'Google Maps Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
