# Generated by Django 5.2.8 on 2025-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_googlemapssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StipeKeySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_key', models.CharField(help_text='Public key for Stripe payment gateway', max_length=255, verbose_name='Stripe Public Key')),
                ('secret_key', models.CharField(help_text='Secret key for Stripe payment gateway', max_length=255, verbose_name='Stripe Secret Key')),
                ('webhook_secret', models.CharField(blank=True, help_text='Starts with whsec_... Get this from Stripe Dashboard → Developers → Webhooks', max_length=255, null=True, verbose_name='Webhook Secret')),
                ('currency', models.CharField(default='USD', help_text='Default currency for Stripe transactions', max_length=3, verbose_name='Default Currency')),
                ('version', models.CharField(help_text='API version for Stripe integration', max_length=50, verbose_name='Stripe API Version')),
            ],
            options={
                'verbose_name': 'Stripe Key Setting',
                'verbose_name_plural': 'Stripe Key Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
