# Generated by Django 5.2.8 on 2025-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_stipekeysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, help_text='Notification settings file name', max_length=255, null=True, verbose_name='file name')),
                ('config_file', models.FileField(help_text='Notification settings configuration file', upload_to='firebase/', verbose_name='config file')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification settings were created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the notification settings were last updated', verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Firebase Setting',
                'verbose_name_plural': 'Firebase Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
