# Generated by Django 5.2.8 on 2025-11-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='business.business', verbose_name='Business'),
        ),
    ]
