# Generated by Django 5.2.8 on 2025-12-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessimage_options_businessoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icon'),
        ),
    ]
