# Generated by Django 5.2.8 on 2025-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businesscategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoffer',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code'),
        ),
    ]
