# Generated by Django 5.2.8 on 2025-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessoffer_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoffer',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular'),
        ),
    ]
