# Generated by Django 5.2.8 on 2025-12-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessoffer_is_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessoffer',
            options={'verbose_name': 'Business Offer', 'verbose_name_plural': 'Business Offers'},
        ),
    ]
