# Generated by Django 5.2.8 on 2025-12-18 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_businessoffer_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Redeemed At')),
                ('is_used', models.BooleanField(default=True, verbose_name='Is Used')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_by', to='business.businessoffer', verbose_name='Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_offers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Redeemed Offer',
                'verbose_name_plural': 'Redeemed Offers',
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
