# Generated by Django 5.2.8 on 2026-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_address_appdownloadlink_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('banner_title', models.TextField(blank=True, null=True, verbose_name='Banner Title')),
                ('banner_description', models.TextField(blank=True, null=True, verbose_name='Banner Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='landing_page/', verbose_name='Banner Image')),
                ('business_section_title', models.TextField(blank=True, null=True, verbose_name='Business Section Title')),
                ('business_section_description', models.TextField(blank=True, null=True, verbose_name='Business Section Description')),
                ('card_section_title', models.TextField(blank=True, null=True, verbose_name='Card Section Title')),
                ('card_section_description', models.TextField(blank=True, null=True, verbose_name='Card Section Description')),
                ('card_section_image', models.ImageField(blank=True, null=True, upload_to='landing_page/', verbose_name='Card Section Image')),
                ('news_section_title', models.TextField(blank=True, null=True, verbose_name='News Section Title')),
                ('news_section_description', models.TextField(blank=True, null=True, verbose_name='News Section Description')),
                ('touch_section_title', models.TextField(blank=True, null=True, verbose_name='Get in Touch Section Title')),
                ('touch_section_description', models.TextField(blank=True, null=True, verbose_name='Get in Touch Section Description')),
                ('faq_section_title', models.TextField(blank=True, null=True, verbose_name='FAQ Section Title')),
                ('faq_section_description', models.TextField(blank=True, null=True, verbose_name='FAQ Section Description')),
                ('footer_section_title', models.TextField(blank=True, null=True, verbose_name='Footer Section Title')),
                ('footer_section_description', models.TextField(blank=True, null=True, verbose_name='Footer Section Description')),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Contents',
            },
        ),
    ]
